<?xml version='1.0' encoding='utf8'?>
<testsuite failures="3" name="delete_cluster.Negative tests for cluster deletion" skips="0" tests="4" time="0.046"><testcase classname="delete_cluster.Negative tests for cluster deletion" name="User can create cluster with name &quot;cluster-QA&quot;" time="0.017"><failure message="None" type="NoneType">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 753, in run
    match.run(runner.context)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1045, in run
    self.func(context, *args, **kwargs)
  File "/home/lobankovyy/EHO/savanna/behave/features/steps/then_steps.py", line 9, in chkStatus
    assert status_code == int(res_code.strip())
AssertionError

Captured stdout:
URL = http://127.0.0.1:8080/v0.2/6b26f08455ec449ea7a2d3da75339255/clusters
data = {"cluster": {"node_templates": {"jt_nn.medium": 1, "tt_dn.small": 1}, "name": "cluster-QA", "base_image_id": "d9342ba8-4c51-441c-8d5b-f9e14a901299"}}
response = 400

400 == 202

Captured logging:
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:requests.packages.urllib3.connectionpool:"POST /v0.2/6b26f08455ec449ea7a2d3da75339255/clusters HTTP/1.1" 400 129</failure><system-out>
<![CDATA[Steps:
       Given cluster data ... passed
        When User create cluster ... passed
        Then Response is "202" ... failed

Captured stdout:
URL = http://127.0.0.1:8080/v0.2/6b26f08455ec449ea7a2d3da75339255/clusters
data = {"cluster": {"node_templates": {"jt_nn.medium": 1, "tt_dn.small": 1}, "name": "cluster-QA", "base_image_id": "d9342ba8-4c51-441c-8d5b-f9e14a901299"}}
response = 400

400 == 202

]]>
</system-out></testcase><testcase classname="delete_cluster.Negative tests for cluster deletion" name="User can get cluster by ID" time="0.014"><failure message="None" type="NoneType">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 753, in run
    match.run(runner.context)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1045, in run
    self.func(context, *args, **kwargs)
  File "/home/lobankovyy/EHO/savanna/behave/features/steps/then_steps.py", line 9, in chkStatus
    assert status_code == int(res_code.strip())
AssertionError

Captured stdout:
URL = http://127.0.0.1:8080/v0.2/6b26f08455ec449ea7a2d3da75339255/clusters/18fadbed48df4ee99153160a977f62cd
response = 500

500 == 200

Captured logging:
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:requests.packages.urllib3.connectionpool:"GET /v0.2/6b26f08455ec449ea7a2d3da75339255/clusters/18fadbed48df4ee99153160a977f62cd HTTP/1.1" 500 109</failure><system-out>
<![CDATA[Steps:
        When User get cluster with id: "0" ... passed
        Then Response is "200" ... failed
         And Response for list cluster by id is:"{u'status': u'Active', u'service_urls': {}, u'name': u'cluster-QA', u'base_image_id': u'd9342ba8-4c51-441c-8d5b-f9e14a901299', u'node_templates': {u'jt_nn.medium': 1, u'tt_dn.small': 1}, u'nodes': []}" ... skipped

Captured stdout:
URL = http://127.0.0.1:8080/v0.2/6b26f08455ec449ea7a2d3da75339255/clusters/18fadbed48df4ee99153160a977f62cd
response = 500

500 == 200

]]>
</system-out></testcase><testcase classname="delete_cluster.Negative tests for cluster deletion" name="User can delete cluster with name &quot;cluster-QA&quot; by ID" time="0.016"><failure message="None" type="NoneType">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 753, in run
    match.run(runner.context)
  File "/usr/local/lib/python2.7/dist-packages/behave/model.py", line 1045, in run
    self.func(context, *args, **kwargs)
  File "/home/lobankovyy/EHO/savanna/behave/features/steps/then_steps.py", line 9, in chkStatus
    assert status_code == int(res_code.strip())
AssertionError

Captured stdout:
URL = http://127.0.0.1:8080/v0.2/6b26f08455ec449ea7a2d3da75339255/clusters/18fadbed48df4ee99153160a977f62cd
response = 500

500 == 204

Captured logging:
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): 127.0.0.1
DEBUG:requests.packages.urllib3.connectionpool:"DELETE /v0.2/6b26f08455ec449ea7a2d3da75339255/clusters/18fadbed48df4ee99153160a977f62cd HTTP/1.1" 500 78</failure><system-out>
<![CDATA[Steps:
        When User delete cluster with id: "0" ... passed
        Then Response is "204" ... failed

Captured stdout:
URL = http://127.0.0.1:8080/v0.2/6b26f08455ec449ea7a2d3da75339255/clusters/18fadbed48df4ee99153160a977f62cd
response = 500

500 == 204

]]>
</system-out></testcase><testcase classname="delete_cluster.Negative tests for cluster deletion" name="User can delete cluster with name &quot;cluster-QA&quot; by ID #No validation" time="0.0"><system-out>
<![CDATA[Steps:
]]>
</system-out></testcase></testsuite>